apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-argo-app

spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: http